[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]
auto-format = true

[language-server.typescript-language-server]
command = "/home/pete/.nvm/versions/node/v20.19.5/bin/typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

[language-server.typescript-language-server.config.preferences]
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayFunctionParameterTypeHints = true
includeInlayVariableTypeHints = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayEnumMemberValueHints = true
